services:
  geth: # サービス名
    container_name: geth # コンテナ名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/Dockerfile
    volumes: # マウントディレクトリ
      - geth_data:/root/.ethereum # データを永続化
    ports:
      - "8545:8545" # RPC ポート
      - "8546:8546" # WebSocket ポート
      - "30303:30303" # P2P ポート
    entrypoint:
      - /bin/sh
    tty: true

volumes:
  geth_data: