services:
  geth: # サービス名
    container_name: geth # コンテナ名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/geth/Dockerfile
    volumes: # マウントディレクトリ
      - geth_data:/root/.ethereum # データを永続化
    ports:
      - "8545:8545" # RPC ポート
      - "8546:8546" # WebSocket ポート
      - "30303:30303" # P2P ポート
    entrypoint:
      - /bin/sh
    tty: true

  go:
    container_name: go
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/go/Dockerfile
    volumes:
    - ./src:/src # マウントディレクトリ
    ports:
      - "8080:8080" # ポート番号
    tty: true # コンテナの永続化
    env_file:
      - ./build/go/.env.local
    environment:
      - TZ=Asia/Tokyo

volumes:
  geth_data: